# Generated by Django 4.2.4 on 2023-08-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("laptop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="laptop",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
