# Generated by Django 4.2.4 on 2023-08-13 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("laptop", "0002_alter_laptop_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="laptop",
            name="storage_location",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="laptop.storagelocation",
            ),
        ),
    ]
