# Generated by Django 4.2.4 on 2023-08-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("laptop", "0004_manufacturer_laptop_manufacturer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="laptop",
            name="vendors",
            field=models.ManyToManyField(to="laptop.vendor"),
        ),
    ]
